# Generated by Django 4.2.7 on 2023-11-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logentry',
            table='log_entries',
        ),
    ]
