# Generated by Django 4.2.7 on 2023-11-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_logentry_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logentry',
            table=None,
        ),
    ]
