# Generated by Django 4.2.7 on 2023-11-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_logentry_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logentry',
            table='api_logentry',
        ),
    ]
