# Generated by Django 4.2.7 on 2023-11-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_logentry_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='timestamp',
        ),
        migrations.AlterModelTable(
            name='logentry',
            table='log_selected',
        ),
    ]
