# Generated by Django 4.2.7 on 2023-11-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_logentry_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logentry',
            table='log_entries',
        ),
    ]
