query_dict = {
    '편의점' : "SELECT * FROM places WHERE category_group_code = 'CS2'; ",
    '대형마켓' : "SELECT * FROM places WHERE category_group_code = 'MT1'; ",
    '아주대학교' : "SELECT * FROM places WHERE place_name = '아주대학교'; ",
    '카페' : "SELECT * FROM places WHERE category_group_code = 'CE7'; ",
    '약국' : "SELECT * FROM places WHERE category_group_code = 'PM9'; ",
    '세탁소' : "SELECT * FROM places WHERE (place_name LIKE '%크린토피아%') OR (place_name LIKE '%빨래%') OR (place_name LIKE '%세탁소%'); " ,
    '부동산' : "SELECT * FROM places WHERE category_group_code = 'AG2'; ",
    '인쇄' : "SELECT * FROM places WHERE category_name LIKE '%인쇄%'; ",
    'PC방' : "SELECT * FROM places WHERE category_name LIKE '%PC방%'; ",
    '내과' : "SELECT * FROM places WHERE category_name LIKE '%내과%'; ",
    '한의원' : "SELECT * FROM places WHERE category_name LIKE '%한의원%'; ",
    '우체국' : "SELECT * FROM places WHERE category_name LIKE '%우체국%'; ",
    '올리브영' : "SELECT * FROM places WHERE category_name LIKE '%올리브영%'; ",
    '영화관' : "SELECT * FROM places WHERE category_name LIKE '%영화관%'; ",
    '헬스장' : "SELECT * FROM places WHERE category_name LIKE '%헬스클럽%'; ",
    '필라테스' : "SELECT * FROM places WHERE category_name LIKE '%필라테스%'; ",
    '코인노래방' : "SELECT * FROM places WHERE category_name LIKE '%코인노래방%'; ",
    '공원' : "SELECT * FROM places WHERE category_name LIKE '%도시근린공원%'; ",
    '맥도날드' : "SELECT * FROM places WHERE category_name LIKE '%맥도날드%'; ",
    '롯데리아' : "SELECT * FROM places WHERE category_name LIKE '%롯데리아%'; ",
    '버거킹' : "SELECT * FROM places WHERE category_name LIKE '%버거킹%'; ",
    '베스킨라빈스' : "SELECT * FROM places WHERE category_name LIKE '%배스킨라빈스%'; ",
    '파리바게뜨' : "SELECT * FROM places WHERE category_name LIKE '%파리바게뜨%'; ",
    '스타벅스' : "SELECT * FROM places WHERE category_name LIKE '%스타벅스%'; ",
    '메가커피' : "SELECT * FROM places WHERE category_name LIKE '%메가MGC커피%'; ",
    '컴포즈커피' : "SELECT * FROM places WHERE category_name LIKE '%컴포즈커피%'; ",
    '빽다방' : "SELECT * FROM places WHERE category_name LIKE '%빽다방%'; ",
    '이디야커피' : "SELECT * FROM places WHERE category_name LIKE '%이디야커피%'; ",
    '투썸플레이스' : "SELECT * FROM places WHERE category_name LIKE '%투썸플레이스%'; ",
    }